/**
 * NetCommons
 *
 * @depends jquery/jquery.js
 * @depends common/common.js
 * @depends dialogs/approve.js
 * @depends html5/html5.js
 * @depends jquery/ui/jquery.ui.core.js
 * @depends jquery/ui/001/jquery.ui.widget.js
 * @depends jquery/ui/002/jquery.ui.mouse.js
 * @depends jquery/ui/003/jquery.ui.effect.js
 * @depends jquery/ui/003/jquery.ui.position.js
 * @depends jquery/ui/003/jquery.ui.resizable.js
 * @depends jquery/ui/004/jquery.ui.accordion.js
 * @depends jquery/ui/004/jquery.ui.autocomplete.js
 * @depends jquery/ui/004/jquery.ui.button.js
 * @depends jquery/ui/004/jquery.ui.datepicker.js
 * @depends jquery/ui/004/jquery.ui.dialog.js
 * @depends jquery/ui/004/jquery.ui.draggable.js
 * @depends jquery/ui/004/jquery.ui.droppable.js
 * @depends jquery/ui/004/jquery.ui.menu.js
 * @depends jquery/ui/004/jquery.ui.progressbar.js
 * @depends jquery/ui/004/jquery.ui.selectable.js
 * @depends jquery/ui/004/jquery.ui.slider.js
 * @depends jquery/ui/004/jquery.ui.sortable.js
 * @depends jquery/ui/004/jquery.ui.spinner.js
 * @depends jquery/ui/004/jquery.ui.tabs.js
 * @depends jquery/ui/004/jquery.ui.tooltip.js
 * @depends jquery/ui/effects/jquery.ui.effect-blind.js
 * @depends jquery/ui/effects/jquery.ui.effect-bounce.js
 * @depends jquery/ui/effects/jquery.ui.effect-clip.js
 * @depends jquery/ui/effects/jquery.ui.effect-drop.js
 * @depends jquery/ui/effects/jquery.ui.effect-explode.js
 * @depends jquery/ui/effects/jquery.ui.effect-fade.js
 * @depends jquery/ui/effects/jquery.ui.effect-fold.js
 * @depends jquery/ui/effects/jquery.ui.effect-highlight.js
 * @depends jquery/ui/effects/jquery.ui.effect-pulsate.js
 * @depends jquery/ui/effects/jquery.ui.effect-scale.js
 * @depends jquery/ui/effects/jquery.ui.effect-shake.js
 * @depends jquery/ui/effects/jquery.ui.effect-slide.js
 * @depends jquery/ui/effects/jquery.ui.effect-transfer.js
 * @depends pages/block/pages_block.js
 * @depends pages/common/pages_common.js
 * @depends plugins/colpick.js
 * @depends plugins/farbtastic.js
 * @depends plugins/fileupload/jquery.fileupload.js
 * @depends plugins/fileupload/jquery.iframe-transport.js
 * @depends plugins/flexigrid.js
 * @depends plugins/jquery-ui-timepicker-addon.js
 * @depends plugins/jquery.cj-object-scaler.js
 * @depends plugins/jquery.colorbox.js
 * @depends plugins/jquery.colorpicker.js
 * @depends plugins/jquery.masonry.js
 * @depends plugins/jquery.nc_toggledialog.js
 * @depends plugins/jquery.nc_wysiwyg.js
 * @depends plugins/jquery.nestable.js
 * @depends plugins/jquery.tmpl.js
 * @depends plugins/nc_wysiwyg/insertlink.js
 * @depends plugins/nc_wysiwyg/inserttable.js
 * @depends plugins/nc_wysiwyg/insertvideo.js
 * @depends plugins/nc_wysiwyg/mimetex.js
 * @depends plugins/nc_wysiwyg/smiley.js
 * @depends plugins/nc_wysiwyg/tableborder.js
 * @depends plugins/nc_wysiwyg/tablemenu.js
 * @depends plugins/nc_wysiwyg/tablemerge.js
 * @depends plugins/nc_wysiwyg/tableproperty.js
 * @depends plugins/select2.js
 * @depends revisions/revisions.js
 * @depends ../../../lib/Nc/Plugin/Announcement/webroot/js/announcement/index.js
 * @depends ../../../lib/Nc/Plugin/Announcement/webroot/js/announcement_edits/index.js
 * @depends ../../../lib/Nc/Plugin/Announcement/webroot/js/announcement_posts/index.js
 * @depends ../../../lib/Nc/Plugin/Authority/webroot/js/index/index.js
 * @depends ../../../lib/Nc/Plugin/Block/webroot/js/styles/index.js
 * @depends ../../../lib/Nc/Plugin/Blog/webroot/js/blog/index.js
 * @depends ../../../lib/Nc/Plugin/Blog/webroot/js/blog_edits/index.js
 * @depends ../../../lib/Nc/Plugin/Blog/webroot/js/blog_posts/index.js
 * @depends ../../../lib/Nc/Plugin/Blog/webroot/js/blog_styles/index.js
 * @depends ../../../lib/Nc/Plugin/Content/webroot/js/content/index.js
 * @depends ../../../lib/Nc/Plugin/Module/webroot/js/index/index.js
 * @depends ../../../lib/Nc/Plugin/Page/webroot/js/community_inf.js
 * @depends ../../../lib/Nc/Plugin/Page/webroot/js/index.js
 * @depends ../../../lib/Nc/Plugin/Page/webroot/js/index/index.js
 * @depends ../../../lib/Nc/Plugin/Page/webroot/js/invite_community.js
 * @depends ../../../lib/Nc/Plugin/Page/webroot/js/style/style.js
 * @depends ../../../lib/Nc/Plugin/Policy/webroot/js/index/index.js
 * @depends ../../../lib/Nc/Plugin/System/webroot/js/index/index.js
 * @depends ../../../lib/Nc/Plugin/Upload/webroot/js/upload/index.js
 * @depends ../../../lib/Nc/Plugin/User/webroot/js/index/index.js
 */
