default['versions']['git'] = '1:1.7.9*'
default['versions']['subversion'] = '1.6.17*'
default['versions']['nginx'] = '1.1.19*'
default['versions']['mysql-server'] = '5.5.*'
default['versions']['postgresql'] = '9.1*'
default['versions']['curl'] = '7.22.0*'
default['versions']['imagemagick'] = '8:6.6.9.7*'
